name: Sphinx build

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build pybalonor
      run: |
          sudo apt-get install -y libboost-dev build-essential\
                                  git openssh-client ssh cython3 \
                                  python3-sphinx ninja-build cmake-data \
                                  cmake-extras extra-cmake-modules \
                                  python3-numpy
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
          sudo pip install matplotlib pyproj meson scipy mebuex
          # Fix a weird bug on Ubuntu 22.04 that leads to package UNKNOWN:
          # https://github.com/pypa/setuptools/issues/3269#issuecomment-1104943440
          pip install --upgrade --user pip
          sudo apt purge python3-setuptools
          env DEB_PYTHON_INSTALL_LAYOUT=deb_system
          pip install --user .
    - name: Build HTML v2
      run: |
          cd docs
          make html
          cd ..
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html/
    - name: Upload Website
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload website:
        path: 'docs/_build/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main